### ISSUE TITLE
registration/login.html doesn't exist

### ISSUE THREAD

**Issue by itsbilal** [enactuswaterloo/website#15]

**Comment by itsbilal** [comment]
Implement something like registration/login.html on this page: https://docs.djangoproject.com/en/1.7/topics/auth/default/#module-django.contrib.auth.views

Use a bootstrap alert for the incorrect password/username message.

**Comment by mmmoussa** [comment]
The login page has been created, fixed, and placed in the correct place. The bootstrap alert is yet to be done.
