### ISSUE TITLE
New Sponsors page

### ISSUE THREAD

**Issue by itsbilal** [enactuswaterloo/website#29]
A new page listing all sponsors, in separate tiers. This would need a new backend model, complete with migrations.

**Comment by pobeng** [comment]
Sponsorship package is now complete. For the sponsor page, I would like to have
-the four tiers of sponsorship, we can add images of the companies' logos
-a link to download our sponsorship package, or to view on another page

**Comment by pobeng** [comment]
I will work on front end design tonight

**Comment by pobeng** [comment]
Done. @itsbilal I added static images for now.
