### ISSUE TITLE
Safari allows profile form to be submitted without client-side validation

### ISSUE THREAD

**Issue by itsbilal** [enactuswaterloo/website#30]
On every major browser except for Safari, client-side validation checks for required elements work just fine; you can't submit a profile form without filling out your first/last name, for instance. However, Safari lets you submit forms without required inputs, which throws an assertion error on the server side, leading to an ugly error message (but the profile isn't saved, which is good).

Ideally the server should redirect back to the form with an error banner at the top.

**Comment by pobeng** [comment]
Working on this today, will have a client-side fix to force required inputs so no server side is needed.

**Comment by pobeng** [comment]
Fixed.
